### ISSUE TITLE
Error API

### ISSUE THREAD

**Issue by hoangvn9x** [MinusGix/MangarockDownloader#7]
https://api.mangarockhd.com/query/
web400/pages?oid=mrs-chapter-100083895&country=United%20States

Today, when I use the app, I get this error : "{"code":109,"data":"Unknown Query Version"}"

**Comment by MinusGix** [comment]
Hm, seems like that web400 part is apart of their api versioning. Changing it to 401 (what I see when I quickly checked the network requests mangarock sends) makes it work.
I uploaded a new version which uses the updated api endpoint, unsure if it works perfectly but it should fix that exact issue. (Also made one spot to change version, for when it inevitably changes in the future)

Redownload the `smallMangaRock.js` script, and replace the old one (or redownload the entire thing) and hopefully it should work now.
