### ISSUE TITLE
Mangarock api

### ISSUE THREAD

**Issue by XanXus96** [MinusGix/MangarockDownloader#9]
please where did you find the api docs i want to use it

**Comment by MinusGix** [comment]
I don't believe there is any API docs.  
I looked at the network traffic that the site does, the various request it makes to it's api (which isn't documented) and acted as the mangarock page would.  
If you want to use their api, then you'll have to look at the requests the sites make and figure out what they do.

**Comment by MinusGix** [comment]
I'm closing this, if you want too ask anything else just comment on this issue again.
